replaced pictures for fan box
tetrabiodistributed/papra pull request #133
Opened 2024-04-09 13:59 UTC by Venkat4real

Continuation of #125

2024-04-15 16:21 UTC, mmroden requested changes
Minor changes

2024-04-15 16:21 UTC, mmroden commented on content/en/v1.1/fan-box.adoc
> +| https://github.com/tetrabiodistributed/papr-print-files/blob/f77c5bc3c5f0d8fadfdf2757c59a09a8cd5e584b/STLs/fan_box/96mm%20Stealth%20Parts/P-TET-000159%20Stealth%20Filter%20Frame%20Sanyo.stl[STL]
This is not the weather gard, but it's the filter frame. https://github.com/tetrabiodistributed/papr-print-files/blob/main/STLs/fan_box/96mm%20Stealth%20Parts/P-TET-000143%20Weather%20Guard.stl (but the permalink) is correct

2024-04-15 16:21 UTC, mmroden commented on content/en/v1.1/fan-box.adoc
> +| https://github.com/tetrabiodistributed/papr-print-files/blob/f77c5bc3c5f0d8fadfdf2757c59a09a8cd5e584b/STLs/fan_box/96mm%20Stealth%20Parts/P-TET-000140%20Base%20Sanyo.st[STL]
Link should end with .stl

2024-04-15 16:21 UTC, mmroden commented on content/en/v1.1/fan-box.adoc
> +| https://octopart.com/9bmb12f201-sanyo+denki-24320259[Link]
Maybe link to the main electronics BOM?  I don't think this is the right fan, but maybe it is.  I thought it ended with 202 not 201

2024-07-19 01:00 UTC, Burhan-Q commented
@Venkat4real looks like there's a few fixes needed, but once addressed this can be merged.

2024-07-19 01:00 UTC, Burhan-Q requested changes

2024-07-19 01:00 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://github.com/tetrabiodistributed/papr-print-files/blob/f77c5bc3c5f0d8fadfdf2757c59a09a8cd5e584b/STLs/fan_box/96mm%20Stealth%20Parts/P-TET-000140%20Base%20Sanyo.st[STL]
@Venkat4real this link needs to fixing still

2024-07-19 01:00 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +|https://www.amazon.com/STEALTH-Respirator-Filters-Woodworking-Replacement/dp/B09H52LGGW[link]
Maybe make `[Link]` (capitalized "L") for consistency

2024-07-26 02:34 UTC, Venkat4real commented
Closing this PR because the changes are made in the last PR.

2024-07-26 02:34 UTC, closed without merging