made links shorter by adding aliases
tetrabiodistributed/papra pull request #134
Opened 2024-04-14 14:47 UTC by Venkat4real

for the issue #131

2024-07-19 01:05 UTC, Burhan-Q approved these changes
Minor changes requested, but otherwise looks good to go

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://octopart.com/9bmb12f201-sanyo+denki-24320259[Sanyo Denki ]
Please trim the trailing white space

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://www.prusa3d.com/category/original-prusa-mk4/[3D Printer ]
Trim white space

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://www.amazon.com/gp/product/B007ICWAJC[hex screwdriver ]
Trim white space

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://octopart.com/112517-amphenol+rf-50123148[ Jack Connector]
Trim white space

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://www.amazon.com/Cleaning-DreamStation-Diameter-Stainless-Cleaner/dp/B08HLQV2VK/[ CPAP hose cleaner]
Trim white space

2024-07-19 01:05 UTC, Burhan-Q commented on content/en/v1.1/fan-box.adoc
> +| https://www.milwaukeetool.com/Products-Repository/North-America/Hand-Tools/Screwdrivers/48-22-2427[9/16 Nut Driver ]
Trim white space

2024-07-19 02:34 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://octopart.com/9bmb12f201-sanyo+denki-24320259[Sanyo Denki ]
Edited

2024-07-19 02:34 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://www.prusa3d.com/category/original-prusa-mk4/[3D Printer ]
Edited

2024-07-19 02:35 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://www.amazon.com/gp/product/B007ICWAJC[hex screwdriver ]
Edited

2024-07-19 02:35 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://octopart.com/112517-amphenol+rf-50123148[ Jack Connector]
Edited

2024-07-19 02:35 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://www.amazon.com/Cleaning-DreamStation-Diameter-Stainless-Cleaner/dp/B08HLQV2VK/[ CPAP hose cleaner]
edited

2024-07-19 02:36 UTC, Venkat4real commented on content/en/v1.1/fan-box.adoc
> +| https://www.milwaukeetool.com/Products-Repository/North-America/Hand-Tools/Screwdrivers/48-22-2427[9/16 Nut Driver ]
edited

2024-07-19 02:51 UTC, Venkat4real commented
Hi @Burhan-Q thanks for the review. I made the changes suggested.

2024-07-19 12:08 UTC, Burhan-Q commented on new 
I don't think you want to add this to the repo. Also, now that it's here, you probably need to remove this key

2024-07-19 12:08 UTC, Burhan-Q commented on new .pub
This should also not be included

2024-07-19 12:09 UTC, Burhan-Q requested changes
Remove SSH files. Revoke SSH private key to prevent someone else from using it (guaranteed it's already compromised).

2024-07-19 12:47 UTC, Venkat4real commented
Sorry, removed the files now.

2024-07-19 19:23 UTC, Burhan-Q approved these changes

2024-07-23 06:27 UTC, capsulecorplab requested changes
Should remove [.vscode/settings.json](https://github.com/tetrabiodistributed/papra/pull/134/files#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357) since we're not using Antora. Otherwise, LGTM

2024-07-23 14:36 UTC, Venkat4real commented
@capsulecorplab Removed the settings.json file.

2024-07-23 20:08 UTC, capsulecorplab commented
Thanks @Venkat4real ! Though it looks like you closed the PR without merging. Would you mind re-opening?

2024-07-24 03:16 UTC, Venkat4real commented
Hi Sean @capsulecorplab . I reopened the PR

2024-07-24 05:26 UTC, capsulecorplab approved these changes

2024-07-24 05:27 UTC, merged